// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyInitRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeyInitResponse {
    #[prost(enumeration = "Coordinate", tag = "1")]
    pub mouse_coordinate: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeyStateRequest {
    #[prost(enumeration = "Key", tag = "1")]
    pub key: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeyStateResponse {
    #[prost(enumeration = "KeyState", tag = "1")]
    pub state: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MouseRequest {
    #[prost(int32, tag = "1")]
    pub width: i32,
    #[prost(int32, tag = "2")]
    pub height: i32,
    #[prost(int32, tag = "3")]
    pub x: i32,
    #[prost(int32, tag = "4")]
    pub y: i32,
    #[prost(enumeration = "MouseAction", tag = "5")]
    pub action: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MouseResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeyRequest {
    #[prost(enumeration = "Key", tag = "1")]
    pub key: i32,
    #[prost(float, tag = "2")]
    pub down_ms: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeyResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeyDownRequest {
    #[prost(enumeration = "Key", tag = "1")]
    pub key: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeyDownResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeyUpRequest {
    #[prost(enumeration = "Key", tag = "1")]
    pub key: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct KeyUpResponse {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Key {
    A = 0,
    B = 1,
    C = 2,
    D = 3,
    E = 4,
    F = 5,
    G = 6,
    H = 7,
    I = 8,
    J = 9,
    K = 10,
    L = 11,
    M = 12,
    N = 13,
    O = 14,
    P = 15,
    Q = 16,
    R = 17,
    S = 18,
    T = 19,
    U = 20,
    V = 21,
    W = 22,
    X = 23,
    Y = 24,
    Z = 25,
    Zero = 26,
    One = 27,
    Two = 28,
    Three = 29,
    Four = 30,
    Five = 31,
    Six = 32,
    Seven = 33,
    Eight = 34,
    Nine = 35,
    F1 = 36,
    F2 = 37,
    F3 = 38,
    F4 = 39,
    F5 = 40,
    F6 = 41,
    F7 = 42,
    F8 = 43,
    F9 = 44,
    F10 = 45,
    F11 = 46,
    F12 = 47,
    Up = 48,
    Down = 49,
    Left = 50,
    Right = 51,
    Home = 52,
    End = 53,
    PageUp = 54,
    PageDown = 55,
    Insert = 56,
    Delete = 57,
    Ctrl = 58,
    Enter = 59,
    Space = 60,
    Tilde = 61,
    Quote = 62,
    Semicolon = 63,
    Comma = 64,
    Period = 65,
    Slash = 66,
    Esc = 67,
    Shift = 68,
    Alt = 69,
    Backspace = 70,
}
impl Key {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::A => "A",
            Self::B => "B",
            Self::C => "C",
            Self::D => "D",
            Self::E => "E",
            Self::F => "F",
            Self::G => "G",
            Self::H => "H",
            Self::I => "I",
            Self::J => "J",
            Self::K => "K",
            Self::L => "L",
            Self::M => "M",
            Self::N => "N",
            Self::O => "O",
            Self::P => "P",
            Self::Q => "Q",
            Self::R => "R",
            Self::S => "S",
            Self::T => "T",
            Self::U => "U",
            Self::V => "V",
            Self::W => "W",
            Self::X => "X",
            Self::Y => "Y",
            Self::Z => "Z",
            Self::Zero => "Zero",
            Self::One => "One",
            Self::Two => "Two",
            Self::Three => "Three",
            Self::Four => "Four",
            Self::Five => "Five",
            Self::Six => "Six",
            Self::Seven => "Seven",
            Self::Eight => "Eight",
            Self::Nine => "Nine",
            Self::F1 => "F1",
            Self::F2 => "F2",
            Self::F3 => "F3",
            Self::F4 => "F4",
            Self::F5 => "F5",
            Self::F6 => "F6",
            Self::F7 => "F7",
            Self::F8 => "F8",
            Self::F9 => "F9",
            Self::F10 => "F10",
            Self::F11 => "F11",
            Self::F12 => "F12",
            Self::Up => "Up",
            Self::Down => "Down",
            Self::Left => "Left",
            Self::Right => "Right",
            Self::Home => "Home",
            Self::End => "End",
            Self::PageUp => "PageUp",
            Self::PageDown => "PageDown",
            Self::Insert => "Insert",
            Self::Delete => "Delete",
            Self::Ctrl => "Ctrl",
            Self::Enter => "Enter",
            Self::Space => "Space",
            Self::Tilde => "Tilde",
            Self::Quote => "Quote",
            Self::Semicolon => "Semicolon",
            Self::Comma => "Comma",
            Self::Period => "Period",
            Self::Slash => "Slash",
            Self::Esc => "Esc",
            Self::Shift => "Shift",
            Self::Alt => "Alt",
            Self::Backspace => "Backspace",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "A" => Some(Self::A),
            "B" => Some(Self::B),
            "C" => Some(Self::C),
            "D" => Some(Self::D),
            "E" => Some(Self::E),
            "F" => Some(Self::F),
            "G" => Some(Self::G),
            "H" => Some(Self::H),
            "I" => Some(Self::I),
            "J" => Some(Self::J),
            "K" => Some(Self::K),
            "L" => Some(Self::L),
            "M" => Some(Self::M),
            "N" => Some(Self::N),
            "O" => Some(Self::O),
            "P" => Some(Self::P),
            "Q" => Some(Self::Q),
            "R" => Some(Self::R),
            "S" => Some(Self::S),
            "T" => Some(Self::T),
            "U" => Some(Self::U),
            "V" => Some(Self::V),
            "W" => Some(Self::W),
            "X" => Some(Self::X),
            "Y" => Some(Self::Y),
            "Z" => Some(Self::Z),
            "Zero" => Some(Self::Zero),
            "One" => Some(Self::One),
            "Two" => Some(Self::Two),
            "Three" => Some(Self::Three),
            "Four" => Some(Self::Four),
            "Five" => Some(Self::Five),
            "Six" => Some(Self::Six),
            "Seven" => Some(Self::Seven),
            "Eight" => Some(Self::Eight),
            "Nine" => Some(Self::Nine),
            "F1" => Some(Self::F1),
            "F2" => Some(Self::F2),
            "F3" => Some(Self::F3),
            "F4" => Some(Self::F4),
            "F5" => Some(Self::F5),
            "F6" => Some(Self::F6),
            "F7" => Some(Self::F7),
            "F8" => Some(Self::F8),
            "F9" => Some(Self::F9),
            "F10" => Some(Self::F10),
            "F11" => Some(Self::F11),
            "F12" => Some(Self::F12),
            "Up" => Some(Self::Up),
            "Down" => Some(Self::Down),
            "Left" => Some(Self::Left),
            "Right" => Some(Self::Right),
            "Home" => Some(Self::Home),
            "End" => Some(Self::End),
            "PageUp" => Some(Self::PageUp),
            "PageDown" => Some(Self::PageDown),
            "Insert" => Some(Self::Insert),
            "Delete" => Some(Self::Delete),
            "Ctrl" => Some(Self::Ctrl),
            "Enter" => Some(Self::Enter),
            "Space" => Some(Self::Space),
            "Tilde" => Some(Self::Tilde),
            "Quote" => Some(Self::Quote),
            "Semicolon" => Some(Self::Semicolon),
            "Comma" => Some(Self::Comma),
            "Period" => Some(Self::Period),
            "Slash" => Some(Self::Slash),
            "Esc" => Some(Self::Esc),
            "Shift" => Some(Self::Shift),
            "Alt" => Some(Self::Alt),
            "Backspace" => Some(Self::Backspace),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum KeyState {
    Pressed = 0,
    Released = 1,
}
impl KeyState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pressed => "Pressed",
            Self::Released => "Released",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Pressed" => Some(Self::Pressed),
            "Released" => Some(Self::Released),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MouseAction {
    Move = 0,
    Click = 1,
    ScrollDown = 2,
}
impl MouseAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Move => "Move",
            Self::Click => "Click",
            Self::ScrollDown => "ScrollDown",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Move" => Some(Self::Move),
            "Click" => Some(Self::Click),
            "ScrollDown" => Some(Self::ScrollDown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Coordinate {
    Screen = 0,
    Relative = 1,
}
impl Coordinate {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Screen => "Screen",
            Self::Relative => "Relative",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Screen" => Some(Self::Screen),
            "Relative" => Some(Self::Relative),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod key_input_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct KeyInputClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl KeyInputClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> KeyInputClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> KeyInputClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            KeyInputClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn init(
            &mut self,
            request: impl tonic::IntoRequest<super::KeyInitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::KeyInitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/input.KeyInput/Init");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("input.KeyInput", "Init"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn key_state(
            &mut self,
            request: impl tonic::IntoRequest<super::KeyStateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::KeyStateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/input.KeyInput/KeyState");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("input.KeyInput", "KeyState"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn send_mouse(
            &mut self,
            request: impl tonic::IntoRequest<super::MouseRequest>,
        ) -> std::result::Result<tonic::Response<super::MouseResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/input.KeyInput/SendMouse");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("input.KeyInput", "SendMouse"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn send(
            &mut self,
            request: impl tonic::IntoRequest<super::KeyRequest>,
        ) -> std::result::Result<tonic::Response<super::KeyResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/input.KeyInput/Send");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("input.KeyInput", "Send"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn send_up(
            &mut self,
            request: impl tonic::IntoRequest<super::KeyUpRequest>,
        ) -> std::result::Result<tonic::Response<super::KeyUpResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/input.KeyInput/SendUp");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("input.KeyInput", "SendUp"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn send_down(
            &mut self,
            request: impl tonic::IntoRequest<super::KeyDownRequest>,
        ) -> std::result::Result<
            tonic::Response<super::KeyDownResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/input.KeyInput/SendDown");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("input.KeyInput", "SendDown"));
            self.inner.unary(req, path, codec).await
        }
    }
}
